# Tarefa 01 - Análise e Visualização de Dados

- Utilizando o arquivo 'caso.csv', fazer uma análise das variáveis e propor atilização para elas e o fundamento para uma razão com outra, caso houver.

In [3]:
import pandas as pd

# iniciando a carga
df = pd.read_csv('/content/caso.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257014 entries, 0 to 257013
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   date                            257014 non-null  object
 1   state                           257014 non-null  object
 2   city                            254251 non-null  object
 3   place_type                      257014 non-null  object
 4   confirmed                       257014 non-null  int64
 5   deaths                          257014 non-null  int64
 6   order_for_place                 257014 non-null  int64
 7   is_last                         257014 non-null  bool
 8   estimated_population_2019       255548 non-null  float64
 9   city_ibge_code                  255548 non-null  float64
 10  confirmed_per_100k_inhabitants  249555 non-null  float64
 11  death_rate                      257014 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(4)
memory usage: 21.8+ MB

## Análise das variáveis

- **date**: Date de coleta dos dados no formato YYYY-MM-DD.
- **state**: Sigla da unidade federativa.
- **city**: Nome do município.
- **place_type**: Tipo de local que esse registro descreve, pode ser city ou state.
- **confirmed**: Número de casos confirmados.
- **deaths**: Número de mortes.                          
- **order_for_place**: Número que identifica a ordem do registro para este local. O registro referente ao primeiro boletim em que esse local aparecer será contabilizado como 1 e os demais boletins incrementarão esse valor.
- **is_last**: Campo pré-computado que diz se esse registro é o mais novo para esse local.                     
- **estimated_population_2019**: População estimada para esse município/estado em 2019.
- **city_ibge_code**: Código IBGE do local.
- **confirmed_per_100k_inhabitants**: Número de casos confirmados por 100.000 habitantes.
- **death_rate**: Taxa de mortalidade (mortes / confirmados).

In [5]:
df.describe()

           confirmed  ...     death_rate
count  257014.000000  ...  257014.000000
mean      234.377707  ...       0.057487
std      2989.141716  ...       0.155919
min         0.000000  ...       0.000000
25%         2.000000  ...       0.000000
50%         7.000000  ...       0.000000
75%        34.000000  ...       0.045500
max    248587.000000  ...       1.000000

[8 rows x 7 columns]

In [6]:
df.sample(5)

              date state  ... confirmed_per_100k_inhabitants death_rate
19799   2020-05-22    CE  ...                      111.88811     0.1500
246870  2020-06-22    SP  ...                       58.82353     0.0769
110175  2020-04-10    MG  ...                        9.31667     0.0189
174334  2020-04-24    RN  ...                       25.82144     0.2500
46003   2020-05-19    BA  ...                        1.26558     0.0000

[5 rows x 12 columns]

In [7]:
print('Casos confirmados por estado: \n')
df[(df['is_last'] == True) & (df['place_type'] == 'state')][['state', 'confirmed']]

Casos confirmados por estado:

       state  confirmed
0         AL      32065
5554      AP      27415
6702      AM      67267
10962     AC      12304
12370     ES      40406
18045     CE     103118
30334     DF      38871
30644     BA      54291
48693     GO      20377
57496     MS       6523
60699     MA      74925
72701     MT      12601
78227     PB      40824
87042     PA      96472
96229     MG      32769
123985    PI      18023
132853    PE      55136
144576    RJ     105897
151838    PR      17822
168139    RR      11872
169248    RO      18173
171753    RN      22665
178946    RS      23060
198054    SE      21081
202193    TO       9425
206971    SC      21951
221930    SP     248587

In [8]:
print('Estado com maior número de casos confirmados:')
df[df['confirmed'] == df['confirmed'].max()][['state', 'confirmed']]

Estado com maior número de casos confirmados:

       state  confirmed
221930    SP     248587

In [9]:
print('Mortes por estado: \n')
df[(df['is_last'] == True) & (df['place_type'] == 'state')][['state', 'deaths']]

Mortes por estado:

       state  deaths
0         AL     958
5554      AP     394
6702      AM    2731
10962     AC     335
12370     ES    1490
18045     CE    5895
30334     DF     509
30644     BA    1601
48693     GO     384
57496     MS      61
60699     MA    1871
72701     MT     476
78227     PB     842
87042     PA    4803
96229     MG     806
123985    PI     574
132853    PE    4488
144576    RJ    9450
151838    PR     539
168139    RR     271
169248    RO     467
171753    RN     858
178946    RS     500
198054    SE     554
202193    TO     183
206971    SC     289
221930    SP   13759

In [10]:
print('Estado com maior número de mortes:')
df[df['confirmed'] == df['confirmed'].max()][['state', 'deaths']]

Estado com maior número de mortes:

       state  deaths
221930    SP   13759

In [11]:
print('Casos confirmados sem morte: ')
df['casos sem morte'] = df['confirmed'] - df['deaths']
df.sample(5)

Casos confirmados sem morte:

              date state  ... death_rate casos sem morte
221849  2020-04-27    SC  ...     0.0000               1
70048   2020-06-20    MA  ...     0.0135              73
159155  2020-05-16    PR  ...     0.0000               1
246539  2020-06-25    SP  ...     0.0909              50
22138   2020-04-08    CE  ...     0.0000               1

[5 rows x 13 columns]

In [12]:
print('Casos confirmados e mortes por cidades')
df[(df['is_last'] == True) & (df['place_type'] == 'city')][['city', 'confirmed', 'deaths']]

Casos confirmados e mortes por cidades

                          city  confirmed  deaths
107                     Anadia        174       1
171                  Arapiraca       2320      30
240                    Atalaia        397       6
301     Barra de Santo Antônio         80       4
365        Barra de São Miguel         89       3
...                        ...        ...     ...
256794      Águas de São Pedro          6       0
256871        Álvares Florence          4       0
256899         Álvares Machado         34       1
256958      Álvaro de Carvalho          2       2
257007                    Óleo          1       0

[5029 rows x 3 columns]

In [20]:
cidades = df.loc[df.city.notnull()]
cidades = cidades.loc[cidades.is_last == True]
cidades.sort_values(by=['confirmed'], ascending=False)

              date state  ... death_rate casos sem morte
252911  2020-06-25    SP  ...     0.0579          110517
149898  2020-06-25    RJ  ...     0.1137           48008
21963   2020-06-24    CE  ...     0.0944           30815
30444   2020-06-24    DF  ...     0.0136           32647
9160    2020-06-25    AM  ...     0.0658           24740
...            ...   ...  ...        ...             ...
73094   2020-06-25    MT  ...     0.0000               0
204572  2020-06-24    TO  ...     0.0000               0
203714  2020-06-24    TO  ...     0.0000               0
203185  2020-06-24    TO  ...     0.0000               0
90544   2020-06-25    PA  ...     0.0000               0

[5029 rows x 13 columns]

In [23]:
print('Total de casos confirmados: ')
cidades.confirmed.sum()

Total de casos confirmados:

1218066

In [24]:
print('Total de óbitos: ')
cidades.deaths.sum()

Total de óbitos:

54749